# test against this version of nodejs
environment:
 matrix:
 - nodejs_version: "6"

# install scripts after repo cloning
install:
 - ps: Install-Product node $env:nodejs_version
 - npm install

# post install test scripts
test_script:
 - node --version
 - npm --version
 - npm test

# Don't actually build
build: off
